name: Create JFrog Repo
description: Create a new JFrog repository
title: "Create JFrog Repo"
labels: [ "jfrog", "repo-request" ]
body:
  - type: input
    id: name
    attributes:
      label: Repository Name
      description: Enter the name for the new repository
      placeholder: example-repo-name
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Repository Type
      description: Choose the type of package repository to create
      options:
        - maven
        - npm
        - docker
        - generic
        - nuget
        - pypi
    validations:
      required: true

  - type: dropdown
    id: visibility
    attributes:
      label: Repository Visibility / Class
      description: Select the type of repository
      options:
        - Pre-Built Setup
        - Local
        - Remote
        - Virtual
        - Federated
    validations:
      required: true

  - type: input
    id: remote_url
    attributes:
      label: Remote Repository URL
      description: Required only if you selected **Remote** visibility
      placeholder: https://registry.npmjs.org/
    validations:
      required: false

  - type: textarea
    id: virtual_repos
    attributes:
      label: Repositories to Aggregate
      description: Required only if you selected **Virtual** visibility
      placeholder: |
        - repo-a
        - repo-b
    validations:
      required: false

  - type: textarea
    id: federation_targets
    attributes:
      label: Federation Targets
      description: Required only if you selected **Federated** visibility
      placeholder: |
        - jfrog-node1.example.com
        - jfrog-node2.example.com
    validations:
      required: false
