name: Create JFrog Repo
description: Create a new JFrog repository
title: "Create JFrog Repo"
body:
  - type: input
    id: name
    attributes:
      label: Repository Name
      description: Enter the name for the new repository
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Repository Type
      description: Choose the package type
      options:
        - maven
        - npm
        - docker
        - generic
        - nuget
        - pypi
    validations:
      required: true
