name: JFrog OIDC Validation

on:
  push

permissions:
  id-token: write
  contents: read

jobs:
  validate-oidc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install JFrog CLI
        run: |
          curl -fL https://install-cli.jfrog.io | sh
          sudo mv jfrog /usr/local/bin/

      - name: Enable JFrog CLI debug
        run: echo "JFROG_CLI_LOG_LEVEL=DEBUG" >> $GITHUB_ENV

      - name: Configure OIDC JFrog connection
        env:
          JF_URL: https://trial174qib.jfrog.io
        run: |
          jfrog rt ping --url=$JF_URL --access-token=$(jfrog rt c show | jq -r .access_token)
        continue-on-error: true

      - name: JFrog OIDC Connect Test
        env:
          JF_URL: https://trial174qib.jfrog.io
        run: |
          jfrog config add oidc-server \
            --url=$JF_URL \
            --oidc-provider \
            --interactive=false
          
          jfrog rt ping --server-id=oidc-server
