name: Test JFrog OIDC

on:
  push

permissions:
  id-token: write
  contents: read

jobs:
  jfrog-oidc:
    runs-on: ubuntu-latest
    env:
      JF_URL: https://trial174qib.jfrog.io
      PROVIDER_NAME: github-jfrog
      TOKEN_ID: GitHub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Debug Mode
        run: echo "JFROG_CLI_LOG_LEVEL=DEBUG" >> $GITHUB_ENV

      - name: Install JFrog CLI
        run: curl -fL https://install-cli.jfrog.io | sh

      - name: Add JFrog Connection with OIDC
        run: |
          jf c add $PROVIDER_NAME \
            --url=$JF_URL \
            --oidc-provider-name=$PROVIDER_NAME \
            --oidc-token-id=$TOKEN_ID \
            --interactive=false

      - name: Test connection
        run: jf rt ping
