name: Test JFrog OIDC

on:
  push

permissions:
  id-token: write
  contents: read

jobs:
  jfrog-oidc:
    runs-on: ubuntu-latest
    env:
      JF_URL: https://trial174qib.jfrog.io
      PROVIDER_NAME: github-jfrog
      TOKEN_ID: GitHub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Debug Mode
        run: echo "JFROG_CLI_LOG_LEVEL=DEBUG" >> $GITHUB_ENV

      - name: Install JFrog CLI
        run: curl -fL https://install-cli.jfrog.io | sh

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env: 
          JF_URL: "https://trial174qib.jfrog.io"
          JF_PROJECT: "https://trial174qib.jfrog.io/ui/admin/projects"
        with:
          oidc-provider-name: "github-jfrog"

      - name: Test connection
        run: jf rt ping
