name: Test JFrog OIDC Connection with Debug

on:
  push

permissions:
  id-token: write       # Required for GitHub OIDC
  contents: read        # For actions/checkout and general use

jobs:
  verify-oidc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JFrog CLI with OIDC
        id: setup-jfrog
        uses: jfrog/setup-jfrog-cli@v4
        with:
          oidc-provider-name: test               # Must match what you created in JFrog
        env:
          JF_URL: https://trial174qib.jfrog.io   # Your JFrog instance URL

      - name: Ping JFrog (verify access)
        run: jf rt ping

      - name: Print GitHub OIDC Token Claims (Base64-decoded)
        run: |
          echo "🔍 Decoding OIDC token..."
          TOKEN=$(curl -s -H "Authorization: Bearer $ID_TOKEN" https://token.actions.githubusercontent.com/.well-known/openid-configuration | jq)
          echo "$TOKEN"
        env:
          ID_TOKEN: ${{ steps.setup-jfrog.outputs.id_token }}
