name: Test JFrog OIDC Connection

on:
  push

permissions:
  id-token: write       # Required for OIDC
  contents: read        # Required to checkout code

jobs:
  verify-oidc:
    runs-on: ubuntu-latest
    env:
      JF_URL: https://trial174qib.jfrog.io

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Enable Debug Logging
        run: |
          echo "JFROG_CLI_LOG_LEVEL=DEBUG" >> $GITHUB_ENV

      - name: Install JFrog CLI
        run: curl -fL https://install-cli.jfrog.io | sh

      - name: Verify JFrog CLI
        run: jf --version

      - name: Configure JFrog CLI with OIDC
        run: |
          jf c add github-jfrog \
            --url=$JF_URL \
            --oidc-provider-name=github-jfrog \
            --interactive=false

      - name: Test Ping to JFrog
        run: jf rt ping
